// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Contexts;

#nullable disable

namespace EntityFrameWork_1_5.Migrations
{
    [DbContext(typeof(KargoTakipContex))]
    [Migration("20230322163956_mig_UpdateFatura")]
    partial class mig_UpdateFatura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Entity.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("Model.Entity.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YasaidigiIlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("Model.Entity.SatisTemsilcisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SatisTemsilcisiAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatisTemsilcisiSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SatisTemsilcisis");
                });

            modelBuilder.Entity("Model.Entity.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaturaId")
                        .HasColumnType("int");

                    b.Property<int>("KargoFirmasiId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("SatisTemsilcisiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId")
                        .IsUnique();

                    b.HasIndex("MusteriId");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("Model.Entity.SiparisUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Miktari")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiparisUruns");
                });

            modelBuilder.Entity("Model.Entity.SatisTemsilcisi", b =>
                {
                    b.HasOne("Model.Entity.Siparis", "Siparis")
                        .WithMany("SatisTemsilcisi")
                        .HasForeignKey("SiparisId");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Model.Entity.Siparis", b =>
                {
                    b.HasOne("Model.Entity.Fatura", null)
                        .WithOne("Siparis")
                        .HasForeignKey("Model.Entity.Siparis", "FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Model.Entity.Fatura", b =>
                {
                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Model.Entity.Siparis", b =>
                {
                    b.Navigation("SatisTemsilcisi");
                });
#pragma warning restore 612, 618
        }
    }
}
